### ISSUE TITLE
Add instructions to update user-agent if using a different OS

### ISSUE THREAD

**Issue by bstenart** [cromachina/fanbox-bot#14]
Hi, 

I'd normally write this as a PR but I'm not really sure where you'll want to add this into your README and I also have a possible bug, but it might be my own error somewhere...

I experienced the issues this morning with an older version of the bot not verifying users anymore and updated everything, stepped through your instructions etc and was still getting denied and was wondering to myself why this was - then it dawned on me, I wasn't using a Linux distro but was using windows at the time.

The useragent for my browser had to then be updated as I was just using WSL to SSH in to my digitalocean droplet as per your instructions with the Network Config for Firefox and left it default as per the template (note the comment about not messing with it unless you know what you're doing) until I realized, this also had to change to properly authenticate.

I changed the line to as follows for my own case and everything began to authenticate properly. For how long, who knows - but it worked after an hour or two of not getting anywhere with it getting the bot back online - I've also confirmed a few authentications with this to ensure the bot is working, though it seems to be failing on role assignment and incorrectly responding to some commands... (see further down)

```
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0
```

I'd imagine if you're on a strange Linux distro or Mac or a SteamDeck (for whatever god forsaken reason you'd do this) you'll also need to change the above header - or, even if you just use a different browser... anyway... I'll let you figure out how to write it in the README as it tripped my up until I thought about it for a little bit...

Additionally, this is now also appearing in the log in the latest version - my droplet is quite dated, but, I doubt it's anything to do with that and more something to do with a change in the bot itself or Fanbox, here's the error frequenting the log as the bot started:

```
[2024-07-01 16:30:29,307][ERROR] 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/root/fanbox-bot/main.py", line 377, in update_role_check_all_members_by_txn
    await update_role_check_by_txn(member)
  File "/root/fanbox-bot/main.py", line 367, in update_role_check_by_txn
    role = role_from_supporting_plan(user_data)
  File "/root/fanbox-bot/main.py", line 314, in role_from_supporting_plan
    plan = user_data['supportingPlan']
TypeError: 'NoneType' object is not subscriptable
```

The bot is no longer assigning the roles it seems... but it keeping the record of the role in it's database. I suppose I have to look into this error or see what's going on with the bot? Unless this is a change in the API and the main script has to be updated also? From reading the error it seems to be a change in the data's structure or contents that is returned that's causing issues?

Here's an extract from my config.yml, I only use the one role on my server but have several plans so they all point to the same role. To me, all seems OK.

```
# Add plans IDs and their associated role IDs here.
# The plan ID number on the left hand side must be a string, like '12345', and not 12345
# To get your plan ID, go to https://www.fanbox.cc/manage/plans, then click edit on the plan.
# The plan ID will be in the address bar. Replace '12345' with your own plan ID.
# <ROLE_ID> must be a number, same as above.
# To get the role ID, turn on developer mode in Discord, go to your server settings, then Roles,
# then right click on the role and select "Copy Role ID"
plan_roles:
  '290141': 1043542296932651078
  '290142': 1043542296932651078
  '290159': 1043542296932651078
  '290333': 1043542296932651078
  '290334': 1043542296932651078
  '290336': 1043542296932651078
```

I should also note that when I'm running the following command, the bot just responds with "access granted" even though... it's... uh, not supposed to? lol

```
command ran:
!unbind-user-by-pixiv-id #number-of-the-user-here.

bot response:
Access granted. Please check the server for new channels!
```

So I'm guessing there's some issues right now with this...

Thanks for your work on this bot - it's a game changer.

**Edit: Role assignment seems to be working, I've had a few users authenticate fine and I think had their role appended correctly... that error still flood's the log on boot though.**

**Comment by cromachina** [comment]
Yes there appears to be a discrepancy with user-agents, and I will update the config template and readme to reflect this.

> I should also note that when I'm running the following command, the bot just responds with "access granted" even though... it's... uh, not supposed to? lol

Because you had updated the bot from a very old version, the admin discord ID is now based on a role ID. This probably no longer matches and the bot thinks you are not an admin anymore, and thus tries to just run the authentication path, ignoring any commands.

**Comment by cromachina** [comment]
The error `update_role_check_all_members_by_txn` is when `auto_role_update` is enabled, but there seems to be an error extracting plan data stored for the user. A bad response may have been stored in the database and now it's stuck. I'll look into this.

**Comment by cromachina** [comment]
Okay, I've updated the documentation for the user-agent information: a4c3399a24d1ba39ff4fd0231259d11b8c27c102

I've updated the bot to try to handle the error you are seeing a little better. If a user gets their role incorrectly removed after this change, simply have them authenticate again and the records should hopefully be updated correctly: 2a344774faff09986e549407fa17dbd57f108e12

**Comment by bstenart** [comment]
Hi,

Thanks for the speedy update - I can confirm that was the issue with the Admin Role ID, I've since corrected this - I must've missed this changing within the template when updating the config.

Thanks for updating the error logging and also the README - I'm sure it'll save some headaches and some questions from people.

I wish Fanbox would make a bot like you've created here, but, in some ways, it's probably best it's externally maintained when you look at the history of other bots such as Patreon having far too many permissions and data collecting.

Thanks for all the work you've done on this.
